### ISSUE TITLE
Duda sobre avance de Marco

### ISSUE THREAD

**Issue by Jorge85015** [mmasias/viajeDeMarco#3]
Hola Manuel, una duda, el avance de Marco será el mismo durante todo el día? O sea, si un día camina 9 horas a velocidad de 10 km/h, serán 10 km para las 9 horas del día?

**Comment by mmasias** [comment]
Exacto. Al día siguiente, se recalcula lo las horas y la velocidad de ese día.

**Comment by Jorge85015** [comment]
Sí eso sí, pero, en un mismo día no cambiará la velocidad por hora cada hora verdad

**Comment by mmasias** [comment]
Ahhh, ya entiendo la pregunta. No: en un mismo día mantiene la velocidad y el tiempo. Les afecta solo el clima (y el mono).
